version: '2'
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    privileged: false
    restart: always
    network_mode: bridge
    mem_swappiness: -1 # temp workaround
    ports:
      - '8123:8123'
    environment:
      - PUID=0
      - PGID=101
      - TZ=Europe/Berlin
    volumes:
      - '/volume1/docker/homeassistant:/config'
  deconz:
    image: marthoc/deconz
    container_name: deconz
    privileged: true
    restart: always
    network_mode: bridge
    mem_swappiness: -1 # temp workaround
    ports:
      - '8880:8880'
      - '8443:8443'
      - '5900:5900'
    environment:
      - PUID=0
      - PGID=101
      - DCONZ_WEB_PORT=8880
      - DCONZ_WS_PORT=8443
      - TZ=Europe/Berlin
    volumes:
      - '/volume1/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ'
